### ISSUE TITLE
Could not find a package configuration file provided by "Td"

### ISSUE THREAD

**Issue by sergeydi** [giuseppeM99/tdlua#2]
I got error massage:

_CMake Error at CMakeLists.txt:4 (find_package):
By not providing "FindTd.cmake" in CMAKE_MODULE_PATH this project has asked
CMake to find a package configuration file provided by "Td", but CMake did
not find one.
Could not find a package configuration file provided by "Td" with any of
the following names:
TdConfig.cmake
td-config.cmake
Add the installation prefix of "Td" to CMAKE_PREFIX_PATH or set "Td_DIR" to
a directory containing one of the above files.  If "Td" provides a separate
development package or SDK, be sure it has been installed._

If I use something like:

`cmake -DCMAKE_BUILD_TYPE=Release -Td_DIR=/root/td/tdlib/lib/cmake/Td ..`

I got error:

_CMake Error at CMakeLists.txt:1 (project):
Generator
Unix Makefiles
does not support toolset specification, but toolset
d_DIR=/root/td/tdlib/lib/cmake/Td
was specified.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/root/tdlua/build/CMakeFiles/CMakeOutput.log"._

**Comment by giuseppeM99** [comment]
you have to compile and install tdlib
```git clone https://github.com/tdlib/td
cd td
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j6 VERBOSE=1
sudo make install
```
see
https://github.com/giuseppeM99/tdlua/blob/master/compile.sh#L12

**Comment by sergeydi** [comment]
Thank you. After several minutes of compiling I got:

/root/tdlua/luaIF.cpp:313:9: error: ‘luaL_newlib’ was not declared in this scope; did you mean ‘luaL_openlib’?
  313 |         luaL_newlib(L, tdlua);
      |         ^~~~~~~~~~~
      |         luaL_openlib
/root/tdlua/luaIF.cpp:314:9: error: ‘luaL_setmetatable’ was not declared in this scope; did you mean ‘lua_setmetatable’?
  314 |         luaL_setmetatable(L, "tdlua");
      |         ^~~~~~~~~~~~~~~~~
      |         lua_setmetatable
make[2]: *** [CMakeFiles/tdlua.dir/build.make:89: CMakeFiles/tdlua.dir/luaIF.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/tdlua.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

PS. I use Lua 5.1...

**Comment by giuseppeM99** [comment]
those methods are not avaiable in lua 5.1, you need to use lua >= 5.2 to compile it.
you can try compiling with lua compat (https://github.com/keplerproject/lua-compat-5.3)
to do this you have to
download https://github.com/keplerproject/lua-compat-5.3/blob/master/c-api/compat-5.3.c
download https://github.com/keplerproject/lua-compat-5.3/blob/master/c-api/compat-5.3.h
edit the file luaIF.h and add `#include "compat-5.3.h"` after the first `#include <lua.hpp>`

**Comment by sergeydi** [comment]
I need tdlua for using with openresty. As I know, it use Lua 5.1. May be you know some "true way" how to use tdlua with openresty?

**Comment by giuseppeM99** [comment]
check out https://github.com/giuseppeM99/tdluaJIT
it uses luaJIT to bind tdlib to lua

**Comment by giuseppeM99** [comment]
another thing
openresty uses luajit, tdlua is compatible with luajit and you just need to install it and put `set(LUA_INCLUDE_DIR "/usr/include/luajit-2.1")` in the CMakeLists.txt file before the include directive

**Comment by sergeydi** [comment]
Thank you. It is very helpful.

**Comment by giuseppeM99** [comment]
is this solved?

**Comment by sergeydi** [comment]
Yes.
