### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by Angize** [giuseppeM99/tdlua#5]
how to compiled tdlua ?
I typed the code inside the gate but it did not compile properly

**Comment by Angize** [comment]
CMake Error at CMakeLists.txt:1 (project):
  Generator

    Unix Makefiles

  does not support toolset specification, but toolset

    d_DIR=/root/td/tdlib/lib/cmake/Td

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by giuseppeM99** [comment]
you need to install the compiler, follow the instructions under the tdlib build instruction generator https://tdlib.github.io/td/build.html

**Comment by Angize** [comment]
i install and compiled tdlib and tdlua
error in tdlua.so run :

lua5.3: error loading module 'tdlua' from file '/usr/lib/x86_64-linux-gnu/lua/5.3/tdlua.so':
        /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/x86_64-linux-gnu/lua/5.3/tdlua.so)
