### ISSUE TITLE
Latest Version @Tdlua

### ISSUE THREAD

**Issue by Angize** [giuseppeM99/tdlua#8]
Please put precompiled binary Build with Lua 5.3 and the latest version of tdlib on this channel @tdlua thank you .

**Comment by giuseppeM99** [comment]
building them now, should be ready within the next hour

**Comment by Angize** [comment]
Please send us the construction instructions one by one and in order so that we can make our own

**Comment by giuseppeM99** [comment]
the compile.sh script is there for that reason

**Comment by Angize** [comment]
This command file is corrupt, I tested it

**Comment by Angize** [comment]
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found 

What is the problem?
How can I run compiled TDLIB on another server without getting this error

**Comment by giuseppeM99** [comment]
install the dependencies as shown here
https://tdlib.github.io/td/build.html?language=C%2B%2B
